### PR TITLE
How To play Info

### PR DESCRIPTION
**Pull request by Marthijn-B**
Added expandable cards for each section
Original manual PDF
Sample Screen shot - in lieu of creating proper ones explaining how to navigate through our online game (Just a place holder to show what it can look like

### CODE REVIEW

**Review by mmdonaldson — CHANGES_REQUESTED** [review]
Looks fine except the pdf is quite large (5.43MB). can we use something else instead that is smaller?

**Comment by Marthijn-B** [comment]
OK. Will try to sort something. Maybe break it down into sections.
ie, Start game/ Game play, scoring...
We'll see

**Review by Marthijn-B — COMMENTED** [review]
Changed Rules PDF to only 2 page one

**Comment by mmdonaldson** [comment]
How long does it take to show this page? As it's still 1.75 MB. Unless you have a super good connection this can take a while. The better approach is HTML.

**Review by mmdonaldson — APPROVED** [review]

**Pull request merged**
