### PR TITLE
Js single player

### PR DESCRIPTION
**Pull request by jacobstringer**
Massive Update!
- Play.js changed by Marthijn to include a single player tick box (tick before start game to play with AI)

The rest are my changes:
- Single player mode added
- Simple AI added
- Total refactor of backend
- Documentation added for controllers
- Picks the right number of guild cards for age 3
- Converts money at end of age 3 to points
- JSON object now includes cardhist objects (discards filtered out) and game object (to cross reference current age and round)
- All non-trade related yellow and purple cards now are fully implemented
- MANY bugfixes, including issues with all cards being able to be played and the final card of age 3 having a bug
- City images have had name updates (incorrect spelling meant some wonders did not show)
- Migration scripts deleted (need to create new scripts - there were some bugs with this)

### CODE REVIEW

**Comment by jacobstringer** [comment]
[Single-player mode](https://trello.com/c/ntT2DefT/48-single-player-mode)

**Comment by jacobstringer** [comment]
[User: Guild cards for age 3 (a random selection based on number of players)](https://trello.com/c/thJr7lLD/26-user-guild-cards-for-age-3-a-random-selection-based-on-number-of-players)

**Comment by jacobstringer** [comment]
[User: Guild cards for age 3 (a random selection based on number of players)](https://trello.com/c/thJr7lLD/26-user-guild-cards-for-age-3-a-random-selection-based-on-number-of-players)

**Comment by jacobstringer** [comment]
[Special card/wonder moves (Playing 2 cards at once, playing discards, commerce/guild cards that depend on other played cards)](https://trello.com/c/tOAIuP0b/16-special-card-wonder-moves-playing-2-cards-at-once-playing-discards-commerce-guild-cards-that-depend-on-other-played-cards)

**Comment by jacobstringer** [comment]
[Special card/wonder moves (Playing 2 cards at once, playing discards, commerce/guild cards that depend on other played cards)](https://trello.com/c/tOAIuP0b/16-special-card-wonder-moves-playing-2-cards-at-once-playing-discards-commerce-guild-cards-that-depend-on-other-played-cards)

**Comment by jacobstringer** [comment]
[User: End game calculations and API messaging](https://trello.com/c/0NotvrZi/20-user-end-game-calculations-and-api-messaging)

**Review by mmdonaldson — APPROVED** [review]

**Pull request merged**
